1679172283683	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1679172723958	Sync.SyncScheduler	DEBUG	Going to sleep, doing a quick sync.
1679172723959	Sync.Service	DEBUG	User-Agent: Firefox/111.0 (Linux x86_64) FxSync/1.113.0.20230313175713.desktop
1679172723959	Sync.Service	INFO	Starting sync at 2023-03-18 20:52:03 in browser session Bz57245fkwsY
1679172723960	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1679172723970	Sync.Status	INFO	Resetting Status.
1679172723970	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1679172723971	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1679172723971	FirefoxAccounts	DEBUG	getOAuthToken enter
1679172723972	FirefoxAccounts	TRACE	getCachedToken returning cached token
1679172723972	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1679172723973	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1679172725296	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1679172889450	Sync.SyncScheduler	DEBUG	Woke from sleep.
1679172889450	Sync.SyncScheduler	DEBUG	Online, will sync in 2s.
1679172889451	Sync.SyncScheduler	DEBUG	Next sync in 2000 ms. (why=wake_notification)
1679172889453	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1679172889464	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2152398862 - NS_ERROR_NET_TIMEOUT
1679172889465	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_NET_TIMEOUT\"  nsresult: \"0x804b000e (NS_ERROR_NET_TIMEOUT)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 491\"  data: no]"}
1679172889466	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/204028242/info/collections failed: [Exception... "The connection has timed out"  nsresult: "0x804b000e (NS_ERROR_NET_TIMEOUT)"  location: "<unknown>"  data: no] No traceback available
1679172889466	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1679172889466	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1679172889466	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The connection has timed out"  nsresult: "0x804b000e (NS_ERROR_NET_TIMEOUT)"  location: "<unknown>"  data: no] No traceback available
1679172889468	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=reschedule)
1679172889478	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The connection has timed out"  nsresult: "0x804b000e (NS_ERROR_NET_TIMEOUT)"  location: "<unknown>"  data: no] No traceback available
