1678659696624	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1678659997630	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1678659997691	Sync.SyncScheduler	DEBUG	Woke from sleep.
1678659997691	Sync.SyncScheduler	DEBUG	Online, will sync in 2s.
1678659997691	Sync.SyncScheduler	DEBUG	Next sync in 2000 ms. (why=wake_notification)
1678659997692	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1678659999692	Sync.Service	DEBUG	User-Agent: Firefox/110.0.1 (Linux x86_64) FxSync/1.112.0.20230311000820.desktop
1678659999693	Sync.Service	INFO	Starting sync at 2023-03-12 22:26:39 in browser session bbAdpxgQkBS7
1678659999693	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1678659999697	Sync.Status	INFO	Resetting Status.
1678659999697	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1678659999698	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1678659999698	FirefoxAccounts	DEBUG	getOAuthToken enter
1678659999699	FirefoxAccounts	TRACE	getCachedToken returning cached token
1678659999699	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1678659999700	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1678660002721	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1678660004759	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1678660005594	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile 304
1678660008100	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/204028242/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1678660008100	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1678660008100	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1678660008100	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1678660008101	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=reschedule)
1678660008105	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
